export const obsList = [
  {
    concept: '7e43b05b-b6d8-4eb5-8f37-0b14f5347368',
    obsDatetime: '2023-07-01',
    obsGroup: null,
    groupMembers: [
      {
        concept: '4c43b05b-b6d8-4eb5-8f37-0b14f5347548',
        obsDatetime: '2023-07-02',
        obsGroup: null,
        groupMembers: [],
        comment: '',
        location: null,
        order: null,
        encounter: null,
        voided: false,
        value: null,
        formFieldPath: '',
        formFieldNamespace: '',
        status: '',
        interpretation: '',
        uuid: '',
      },
    ],
    comment: '',
    location: null,
    order: null,
    encounter: null,
    voided: false,
    value: null,
    formFieldPath: '',
    formFieldNamespace: '',
    status: '',
    interpretation: '',
    uuid: '',
  },
];
